### PR TITLE
[oracle] Fix class conflict when using multi cdc sql jar

### LINKED ISSUE #2234: flink-sql-connector-oracle-cdc-2.4.0采集出现异常
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.15.2

### Flink CDC version

2.4.0

### Database and its version

Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

### Minimal reproduce step

CREATE TABLE product_view_source (
`a` String,
`b` String,
PRIMARY KEY (`a`) NOT ENFORCED
) WITH (
'connector' = 'oracle-cdc',
'hostname' = 'ip',
'port' = '1521',
'username' = 'flinkuser',
'password' = 'flinkpw',
'database-name' = 'name',
'schema-name' = 'schema',
'table-name' = 'mytable',
'debezium.log.mining.strategy' = 'online_catalog',
    'debezium.log.mining.continuous.mine' = 'true',
'scan.startup.mode' = 'latest-offset' 
);
select * from product_view_source;

### What did you expect to see?

正常采集

### What did you see instead?

java.lang.NoSuchMethodError: io.debezium.connector.oracle.logminer.LogMinerChangeRecordEmitter.addStaticHeader(Ljava/lang/String;Lcom/ververica/cdc/connectors/shaded/org/apache/kafka/connect/data/SchemaAndValue;)V

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by ruanhang1993**
Fix #2234 .

### CODE REVIEW

File: flink-connector-debezium/src/main/java/io/debezium/relational/RelationalChangeRecordEmitter.java [hunk 1]
```diff
@@ -172,7 +164,7 @@ protected void emitUpdateRecord(Receiver<P> receiver, TableSchema tableSchema)
                     newKey,
                     envelope,
                     getOffset(),
-                    getStaticConnectHeaders());
+                    getEmitConnectHeaders().orElse(null));
```
Comment (leonardBang) [inline flink-connector-debezium/src/main/java/io/debezium/relational/RelationalChangeRecordEmitter.java:167]: I don't catch here, why we use`null` instead of `new ConnectHeaders()`?

Comment (ruanhang1993) [reply flink-connector-debezium/src/main/java/io/debezium/relational/RelationalChangeRecordEmitter.java:167]: The debezium original code uses `null` here.

**Review by leonardBang — APPROVED** [review]
Thanks @ruanhang1993 for the fix, LGTM
