### PR TITLE
[mysql] Reduce the memory usage of JM by sharing table schemas between splits

### LINKED ISSUE #865: [mysql] Too many splitInfo cause OOM of jobmanager
**Describe the bug**

in the issue https://issues.apache.org/jira/browse/FLINK-24855， have some problems when we sync big tables or full database 

**Environment :**
 - Flink version :  1.13.3
 - Flink CDC version:  2.1.1
 - Database and version: mysql-5.7

**To Reproduce**
1. Thes test data :  The data scale more than billion ，and produce more than one hundred thousand enumerator state
2. The test code :  The multiple tables sync by stream api 
3. The error :
Source Coordinator Thread already exists. There should never be more than one thread driving the actions of a Source Coordinator.

**Additional Description**

### PR DESCRIPTION
**Pull request by leonardBang**
The optimization to reduce JM memory usage, this PR aims to resolve #865

### CODE REVIEW

File: flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/state/PendingSplitsStateSerializer.java [hunk 1]
```diff
@@ -205,29 +230,50 @@ private HybridPendingSplitsState deserializeLegacyHybridPendingSplitsState(
...
+                });
+        assignedSnapshotSplits
+                .entrySet()
+                .forEach(
+                        entry -> {
+                            tableSchemas.putAll(entry.getValue().getTableSchemas());
+                            assignedSchemaLessSnapshotSplits.put(
+                                    entry.getKey(), entry.getValue().toSchemaLessSnapshotSplit());
+                        });
+        if (version == 4) {
```
Comment (ruanhang1993) [inline flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/state/PendingSplitsStateSerializer.java:269]: The condition `version >= 4` may be better?

**Review by PatrickRen — APPROVED** [review]
Thanks for the patch @leonardBang! LGTM. Just a minor comment on the serializer that maybe we could add a backward compatibility test for validating new serializers could deserialize state with earlier version.
