### PR TITLE
[sqlserver] Fix backfill stream task hang

### LINKED ISSUE #2366: [Bug] SQL server synchronization with other tables will trigger incremental updates
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.2

### Flink CDC version

2.4.1

### Database and its version

sqlserver2012

### Minimal reproduce step

In a formal environment, (a certain table) is fully synchronized first and then incrementally synchronized. For unknown reasons, incomplete full synchronization will trigger incremental synchronization. In fact, there is no data change in the table, and the program will be in a dormant state. If there is a data change, it will change from incremental to full, and everything seems to be normal again
image

### What did you expect to see?

I hope to be able to complete full synchronization normally before incrementing

### What did you see instead?

The program is unable to synchronize data properly and has been in a paused state

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by GOODBOY008**
close #2366

### CODE REVIEW

**Comment by GOODBOY008** [comment]
cc @Jiabao-Sun @ysq5202121 PTAL.

File: flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/source/reader/fetch/SqlServerStreamFetchTask.java [hunk 1]
```diff
@@ -121,19 +122,17 @@ public LsnSplitReadTask(
...
-        public void afterHandleLsn(
-                SqlServerPartition partition, SqlServerOffsetContext offsetContext) {
+        public void afterHandleLsn(SqlServerPartition partition, Lsn toLsn) {
             // check do we need to stop for fetch binlog for snapshot split.
             if (isBoundedRead()) {
-                final LsnOffset currentRedoLogOffset = getLsnPosition(offsetContext.getOffset());
-                // reach the high watermark, the binlog fetcher should be finished
-                if (currentRedoLogOffset.isAtOrAfter(lsnSplit.getEndingOffset())) {
+                Offset endingOffset = lsnSplit.getEndingOffset();
+                if (toLsn.compareTo(((LsnOffset) endingOffset).getLcn()) >= 0) {
```
Comment (ruanhang1993) [inline flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/source/reader/fetch/SqlServerStreamFetchTask.java:129]: Is `getLcn` the right name?

File: flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/source/reader/fetch/SqlServerStreamFetchTask.java [hunk 2]
```diff
@@ -121,19 +122,17 @@ public LsnSplitReadTask(
...
                     // send binlog end event
                     try {
                         dispatcher.dispatchWatermarkEvent(
                                 partition.getSourcePartition(),
                                 lsnSplit,
-                                currentRedoLogOffset,
+                                endingOffset,
```
Comment (ruanhang1993) [inline flink-connector-sqlserver-cdc/src/main/java/com/ververica/cdc/connectors/sqlserver/source/reader/fetch/SqlServerStreamFetchTask.java:135]: Why should we send `endingOffset` instead of `toLsn` here?

**Review by ruanhang1993 — COMMENTED** [review]
Is it possible to cover this bug with some tests?

LGTM by now.

**Review by ruanhang1993 — APPROVED** [review]
