### PR TITLE
[mysql] Catch and hold exception in chunk splitter thread and rethrow in getNext()

### LINKED ISSUE #1081: 监视千万级别的MYSQL表，全量阶段没有反应。
**Describe the bug(Please use English)**
Use the Initia mode to monitor millions of tables, do not read data, no response;

**Environment :**
 - Flink version :  1.14.3
 - Flink CDC version: 2.2.0
 - Database and version:  MYSQL 8.0.15

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

**Additional Description**
同步ersdata.book_datatype_rel这个1000多万的表，启动后没有任何反应；其他的数据量没有呢么大的表非常正常；

image

### PR DESCRIPTION
**Pull request by PatrickRen**
This pull request fixes #1081 that an exception should be thrown in coordinator thread if the consuming table doesn't have primary key.

### CODE REVIEW

File: flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlSourceITCase.java [hunk 1]
```diff
@@ -248,6 +249,22 @@ public void testTaskManagerFailoverForNewlyAddedTableWithAheadBinlog() throws Ex
                 "address_beijing");
     }
 
+    @Test
+    public void testConsumingTableWithoutPrimaryKey() {
```
Comment (leonardBang) [inline flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlSourceITCase.java:253]: What's the diff between the ITCase and following unit test?

File: flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java [hunk 2]
```diff
@@ -75,13 +76,14 @@ public class MySqlSnapshotSplitAssigner implements MySqlSplitAssigner {
     private final int currentParallelism;
     private final List<TableId> remainingTables;
     private final boolean isRemainingTablesCheckpointed;
+    private final Object lock = new Object();
+    private final AtomicReference<Throwable> uncaughtSplitterException;
```
Comment (leonardBang) [inline flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java:80]: Could we use `volatile Throwable `?

File: flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java [hunk 3]
```diff
@@ -397,6 +386,35 @@ private boolean allSplitsFinished() {
...
+            synchronized (lock) {
+                lock.notify();
+            }
+        }
+    }
+
+    private void checkSplitterErrors() {
+        if (uncaughtSplitterException.get() != null) {
+            throw new RuntimeException(
+                    "Chunk splitting has encountered exception", uncaughtSplitterException.get());
```
Comment (leonardBang) [inline flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java:414]: minor: use `FlinkRuntimeException`

File: flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlSourceITCase.java (hunk 1 above)
Comment (PatrickRen) [reply flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlSourceITCase.java:253]: Basically they are testing the same functionality on different level. Personally I prefer to keep both the unit and integration case because unit test doesn't touch the logic that the exception would finally trigger a job failover.

File: flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java (hunk 2 above)
Comment (PatrickRen) [reply flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java:80]: Sure these two share the same semantic. I'll change it to `volatile` for simplicity.

File: flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlSourceITCase.java (hunk 1 above)
Comment (leonardBang) [reply flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/source/MySqlSourceITCase.java:253]: make sense to me

**Review by leonardBang — APPROVED** [review]
Thanks @PatrickRen for the contribution, LGTM
Could you also open a PR for `release-2.2` ?
