### PR TITLE
 [mysql] Fix the MySqlSnapshotSplitAssigner may assign duplicate splits

### LINKED ISSUE #358: [test] The test testJobManagerFailoverInBinlogPhase failed
https://dev.azure.com/ververica/flink-cdc-connectors/_build/results?buildId=242&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=ce18b30f-11b8-5f1e-8fbd-391708956df7&l=58554

### PR DESCRIPTION
**Pull request by leonardBang**
commit f04fcca104f63c1f4a1fd87948c050229dcd6ebf  Fix #358 
commit  a5334c222207d4168837efb7d28bc7edd2723fe5 Improve test code

### CODE REVIEW

File: flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MysqlTimezoneITCase.java [hunk 1]
```diff
@@ -76,10 +76,7 @@
 
     @Parameterized.Parameters(name = "incrementalSnapshot: {0}")
     public static Object[] parameters() {
-        return new Object[][] {new Object[] {true}
-            //            ,
-            //            new Object[] {false}
-        };
+        return new Object[][] {new Object[] {true}, new Object[] {false}};
```
Comment (wuchong) [inline flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MysqlTimezoneITCase.java:79]: Can be `List<Boolean>`

**Review by wuchong — APPROVED** [review]
