### PR TITLE
[mysql] support to checkpoint in chunk level at the snapshot phase

### LINKED ISSUE #1061: MySQL CDC incremental snapshot reading will duplicate when  a failure happend
**Describe the bug(Please use English)**
The source of snapshot phase can support checkpoint in chunk level. If a failure happens, the source can be restored and continue to read chunks from last finished chunks.

 But the checkpoint will done multiple times in single split.  When the source restored the data will reapeat

**Environment :**
 - Flink version :  1.13.5
 - Flink CDC version:  2.2
 - Database and version:  5.6

### PR DESCRIPTION
**Pull request by ruanhang1993**
This PR supports to checkpoint in chunk level at the snapshot phase.

### CODE REVIEW

File: flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/ChunkSplitter.java [hunk 1]
```diff
@@ -65,54 +66,76 @@ class ChunkSplitter {
...
-            Column chunkKeyColumn =
-                    ChunkUtils.getChunkKeyColumn(table, sourceConfig.getChunkKeyColumn());
-            final List<ChunkRange> chunks;
-            try {
-                chunks = splitTableIntoChunks(jdbc, tableId, chunkKeyColumn);
-            } catch (SQLException e) {
-                throw new FlinkRuntimeException("Failed to split chunks for table " + tableId, e);
-            }
+    /** This method should be invoked before getting chunks for a table. */
+    public void switchSplittingTable(TableId tableId) throws SQLException {
```
Comment (leonardBang) [inline flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/ChunkSplitter.java:83]: We can let `ChunkSplitter` be stateful,  the `ChunkSplitter` can restore from `ChunkSplitterState` and will produce a `ChunkSplitterState` when call `snapshotState()`, the `ChunkSplitterState` consists of multiple fields.  In this way, we can make the code more clean.

File: flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java [hunk 2]
```diff
@@ -83,6 +84,10 @@ public class MySqlSnapshotSplitAssigner implements MySqlSplitAssigner {
 
     @Nullable private Long checkpointIdToFinish;
 
+    @Nullable private TableId splittingTableId;
+    @Nullable private Object chunkStart;
+    @Nullable private Integer chunkId;
+
```
Comment (leonardBang) [inline flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java:90]: we can Encapsulate these fields to `ChunkSplitterState `

File: flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/state/PendingSplitsStateSerializer.java [hunk 3]
```diff
@@ -224,6 +237,19 @@ private SnapshotPendingSplitsState deserializeSnapshotPendingSplitsState(
         }
         List<TableId> remainingTableIds = readTableIds(in);
         boolean isTableIdCaseSensitive = in.readBoolean();
+
+        TableId splittingTableId = null;
+        Object chunkStart = null;
+        Integer chunkId = null;
+        if (splitVersion > 4) {
```
Comment (leonardBang) [inline flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/state/PendingSplitsStateSerializer.java:244]: Should use version of `PendingSplitsState` instead of split's version

File: flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/split/MySqlSplitSerializer.java [hunk 4]
```diff
@@ -47,7 +47,7 @@ public final class MySqlSplitSerializer implements SimpleVersionedSerializer<MyS
 
     public static final MySqlSplitSerializer INSTANCE = new MySqlSplitSerializer();
 
-    private static final int VERSION = 4;
+    private static final int VERSION = 5;
```
Comment (leonardBang) [inline flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/split/MySqlSplitSerializer.java:50]: We should not change this version because we did not change the Split structure, right?

File: flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java [hunk 5]
```diff
@@ -194,11 +211,28 @@ private void startAsynchronouslySplit() {
...
         }
     }
 
+    private void splitUnevenlySizedChunks(TableId tableId) throws SQLException {
+        MySqlSnapshotSplit snapshotSplit;
+        do {
+            snapshotSplit = chunkSplitter.splitOneUnevenlySizedChunk(chunkId, chunkStart);
+            synchronized (lock) {
+                remainingSplits.add(snapshotSplit);
+                chunkStart =
```
Comment (leonardBang) [inline flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java:224]: nextChunkStart

File: flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java [hunk 6]
```diff
@@ -194,11 +211,28 @@ private void startAsynchronouslySplit() {
...
+                        snapshotSplit.getSplitEnd() == null ? null : snapshotSplit.getSplitEnd()[0];
+                chunkId++;
+                if (chunkStart == null) {
```
Comment (leonardBang) [inline flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java:227]: nextChunkStart == CHUNK_END

File: flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java [hunk 7]
```diff
@@ -194,11 +211,28 @@ private void startAsynchronouslySplit() {
...
+                    remainingTables.remove(tableId);
+                    splittingTableId = null;
```
Comment (leonardBang) [inline flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java:229]: currentSplittingTableId

File: flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java [hunk 8]
```diff
@@ -194,11 +211,28 @@ private void startAsynchronouslySplit() {
...
+                }
+                lock.notify();
+            }
+        } while (snapshotSplit.getSplitEnd() != null);
```
Comment (leonardBang) [inline flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java:233]:
```suggestion
        } while (snapshotSplit.getSplitEnd() != CHUNK_END);
```

File: flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java [hunk 9]
```diff
@@ -383,16 +427,43 @@ private boolean allSplitsFinished() {
 
     private void splitChunksForRemainingTables() {
         try {
+            // restore from a checkpoint
+            if (splittingTableId != null) {
+                chunkSplitter.switchSplittingTable(splittingTableId);
+                splitUnevenlySizedChunks(splittingTableId);
```
Comment (leonardBang) [inline flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java:433]: Why restored chunkSplitter must be unEvenly here? The logic is a little confused.

Comment (ruanhang1993) [reply flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java:433]: Only unEvenly table will use the state to store the information. Evenly table will split the table only once and get all of the splits.

**Comment by leonardBang** [comment]
@ruanhang1993 Could you help rebase this PR as there're conflicts now？

**Comment by ruanhang1993** [comment]
> @ruanhang1993 Could you help rebase this PR as there're conflicts now？

Rebased. @leonardBang . Thanks.

File: flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java [hunk 10]
```diff
@@ -146,11 +151,15 @@ private MySqlSnapshotSplitAssigner(
...
         this.isRemainingTablesCheckpointed = isRemainingTablesCheckpointed;
         this.isTableIdCaseSensitive = isTableIdCaseSensitive;
+        this.chunkSplitter =
+                createChunkSplitter(sourceConfig, isTableIdCaseSensitive, chunkSplitterState);
     }
 
     @Override
     public void open() {
-        chunkSplitter = createChunkSplitter(sourceConfig, isTableIdCaseSensitive);
+        if (chunkSplitter != null) {
```
Comment (leonardBang) [inline flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java:160]: hint: chunkSplitter will never null as it construct in constructor

**Review by leonardBang — APPROVED** [review]
Thanks @ruanhang1993 for the contribution, LGTM once fix the minor comment
