### PR TITLE
[postgres] Fix the slot name conflict bug

### LINKED ISSUE #2248: [Bug] PostgreSQL CDC cannot start from a savepoint
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16

### Flink CDC version

2.4.0

### Database and its version

no need

### Minimal reproduce step

enable `scan.incremental.snapshot.enabled` and restart from a savepoint

### What did you expect to see?

PostgreSQL CDC starts from a savepoint successfully

### What did you see instead?

PostgreSQL CDC cannot start from a savepoint

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by ruanhang1993**
Fix #2248 .

TODO: cp to master branch.

### CODE REVIEW

File: flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/enumerator/PostgresSourceEnumerator.java [hunk 1]
```diff
@@ -56,6 +60,20 @@ public void start() {
      * reading the globalStreamSplit to catch all data changes.
      */
     private void createSlotForGlobalStreamSplit() {
+        SlotState slotInfo = null;
+        try (PostgresConnection connection = postgresDialect.openJdbcConnection()) {
+            slotInfo =
+                    connection.getReplicationSlotState(
+                            postgresDialect.getSlotName(), postgresDialect.getPluginName());
+        } catch (SQLException e) {
+            // do nothing
```
Comment (leonardBang) [inline flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/enumerator/PostgresSourceEnumerator.java:69]: It's better to throw a runtime exception, otherwise we may create a duplicated slot  in following code

File: flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLSavepointITCase.java [hunk 2]
```diff
@@ -0,0 +1,261 @@
...
+
+    @Test
+    public void testSavepoint() throws Exception {
+        testRestartFromSavepoint();
+    }
+
+    private void testRestartFromSavepoint() throws Exception {
+        initializePostgresTable(POSTGRES_CONTAINER, "inventory");
+
+        final TemporaryFolder temporaryFolder = new TemporaryFolder();
```
Comment (leonardBang) [inline flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLSavepointITCase.java:63]: minor: remove after use

File: flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLSavepointITCase.java [hunk 3]
```diff
@@ -0,0 +1,261 @@
...
+    private static int sinkSize(String sinkName) {
+        synchronized (TestValuesTableFactory.class) {
+            try {
+                return TestValuesTableFactory.getRawResults(sinkName).size();
+            } catch (IllegalArgumentException e) {
+                // job is not started yet
+                return 0;
+            }
+        }
+    }
```
Comment (leonardBang) [inline flink-connector-postgres-cdc/src/test/java/com/ververica/cdc/connectors/postgres/table/PostgreSQLSavepointITCase.java:260]: These code can be moved to testBase or utils class ?

**Review by leonardBang — COMMENTED** [review]
Thanks @ruanhang1993 for the contribution, I left minor comments

**Review by leonardBang — APPROVED** [review]
Thanks @ruanhang1993 for the update, LGTM
