### PR TITLE
[mysql] fix error when alter sqls contains default string value and collate.

### LINKED ISSUE #1506: DDL Parsing Error When using multiple quotes
**Describe the bug(Please use English)**

MySQLCDC, DataStreamAPI

DDL Parsing Error When using multiple quotes ( **_'....'_** ) after  _DEFAULT VALUE_ 

Expected **0** as default value , but get  string **_0'COLLATE'utf8_general_ci_**

>DDL SQL:
 create table test {
             ...
             is_delete TINYINT DEFAULT VALUE '**_0' COLLATE 'utf8_general_ci_**'
             ...
         }

> ExceptionTrace： 
Caused by: java.lang.NumberFormatException: For input string: "**_0'COLLATE'utf8_general_ci_**"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Short.parseShort(Short.java:118)
        at java.lang.Short.valueOf(Short.java:174)
        at java.lang.Short.valueOf(Short.java:200)
        at io.debezium.jdbc.JdbcValueConverters.lambda$convertSmallInt$40(JdbcValueConverters.java:865)
        at io.debezium.jdbc.JdbcValueConverters.convertValue(JdbcValueConverters.java:1288)
        at io.debezium.jdbc.JdbcValueConverters.convertSmallInt(JdbcValueConverters.java:853)
        at io.debezium.jdbc.JdbcValueConverters.lambda$converter$4(JdbcValueConverters.java:293)
        at io.debezium.connector.mysql.MySqlDefaultValueConverter.setColumnDefaultValue(MySqlDefaultValueConverter.java:405)
        at io.debezium.connector.mysql.antlr.listener.CreateTableParserListener.convertDefaultValueToSchemaType(CreateTableParserListener.java:147)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at io.debezium.connector.mysql.antlr.listener.CreateTableParserListener.lambda$exitColumnCreateTable$1(CreateTableParserListener.java:75)
        at io.debezium.connector.mysql.antlr.MySqlAntlrDdlParser.runIfNotNull(MySqlAntlrDdlParser.java:357)
        at io.debezium.connector.mysql.antlr.listener.CreateTableParserListener.exitColumnCreateTable(CreateTableParserListener.java:55)
        at io.debezium.ddl.parser.mysql.generated.MySqlParser$ColumnCreateTableContext.exitRule(MySqlParser.java:4733)
        at io.debezium.antlr.ProxyParseTreeListenerUtil.delegateExitRule(ProxyParseTreeListenerUtil.java:64)
        at io.debezium.connector.mysql.antlr.listener.MySqlAntlrDdlParserListener.exitEveryRule(MySqlAntlrDdlParserListener.java:106)
        at com.ververica.cdc.connectors.shaded.org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:48)
        at com.ververica.cdc.connectors.shaded.org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:30)
        at com.ververica.cdc.connectors.shaded.org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at com.ververica.cdc.connectors.shaded.org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at com.ververica.cdc.connectors.shaded.org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at com.ververica.cdc.connectors.shaded.org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at io.debezium.antlr.AntlrDdlParser.parse(AntlrDdlParser.java:87)
        at io.debezium.connector.mysql.MySqlDatabaseSchema.parseDdl(MySqlDatabaseSchema.java:213)
        at io.debezium.connector.mysql.MySqlDatabaseSchema.parseStreamingDdl(MySqlDatabaseSchema.java:200)
        at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleQueryEvent(MySqlStreamingChangeEventSource.java:574)
        at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleEvent(MySqlStreamingChangeEventSource.java:352)

**Environment :**
 - Flink version :  1.14
 - Flink CDC version: 2.2
 - Database and version: MySQL 5.7

**To Reproduce**
1. The test data :
2. The test code :
3. The error :

**Additional Description**

### PR DESCRIPTION
**Pull request by ruanhang1993**
This PR fixed #1506.

### CODE REVIEW

File: flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlConnectorITCase.java [hunk 1]
```diff
@@ -1214,6 +1214,80 @@ public void testDdlWithDefaultStringValue() throws Exception {
...
+        tEnv.executeSql(sourceDDL);
+        // async submit job
+        TableResult result = tEnv.executeSql("SELECT * FROM default_value_test");
+        JobClient jobClient = result.getJobClient().get();
+        waitForJobStatus(
+                jobClient,
+                Collections.singletonList(RUNNING),
+                Deadline.fromNow(Duration.ofSeconds(10)));
+        // wait the job totally finishes starting
+        Thread.sleep(10000);
```
Comment (leonardBang) [inline flink-connector-mysql-cdc/src/test/java/com/ververica/cdc/connectors/mysql/table/MySqlConnectorITCase.java:1266]: we can add a method that compares the output result to check the job has started finished

**Review by leonardBang — COMMENTED** [review]
Thanks @ruanhang1993 for the contribution, the PR generally LGTM. I only left one minor comment about the test/
