### PR TITLE
[Mysql] Fix duplicate split which cause duplicate data when open scanNewlyAddedTableEnabled

### LINKED ISSUE #2095: [Bug] Duplicate Split which cause duplicate data when open scanNewlyAddedTableEnabled
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

FLINK 1.13 - FLINK 1.16 (all version)

### Flink CDC version

Latest

### Database and its version

Mysql (all version)

### Minimal reproduce step

1、open scan.newly-added-table.enabled in mysql source
2、running in snapshot phase
3、stop and restart the job

image

The chunks that generated before stop will be generated again in the second start
So the data will be duplicated, this is unacceptable when table contains large chunk of data which will cause a lot of extra tim e

### What did you expect to see?

no duplicate split when job restarts

### What did you see instead?

duplicate split when job restarts

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by EMsnap**
Fix #2095 

I carefully debugged the bug and there is the analysis:

1、In MySqlSnapshotSplitAssigner, split table happens asynchronously
2、After the finish of every table split the table will be moved from remaining table 
3、After tm calls getNext() from  MySqlSnapshotSplitAssigner, the table will be added to alreadyProcessedTables
4、However when job restarts and open scanNewlyAddedTableEnabled and discover newly added table, it gets into the following logic

image

The alreadyProcessedTables + remainingTables won't always be euqals to the tables splitted in the last run.

This happens when table is so large and tm can't process split on time. 

For example:
1、The task reads from A and B, and each of them split into 1000 chunks 
2、The remaingTable is empty since they are already splitted, but alreadyProcessedTables only contains A since B is not fetch by tm now
3、 job restarts and B will be spliited again.

### CODE REVIEW

**Comment by EMsnap** [comment]
@leonardBang @lzshlzsh PLAL

**Comment by ruanhang1993** [comment]
@EMsnap Thanks.
Please rebase the master branch.

**Comment by EMsnap** [comment]
> @EMsnap Thanks. Please rebase the master branch.

Sure, done

Thanks for the update

**Comment by ruanhang1993** [comment]
> > @EMsnap Thanks. Please rebase the master branch.
> 
> Sure, done
> 
> Thanks for the update

Thanks @EMsnap . The CI failed. Please take a look at it.

**Comment by EMsnap** [comment]
> > > @EMsnap Thanks. Please rebase the master branch.
> > 
> > 
> > Sure, done
> > Thanks for the update
> 
> Thanks @EMsnap . The CI failed. Please take a look at it.

image

I guess the failed UT is not related to the pr since the pr works on mysql-cdc, could u help rerun the UT ?

**Comment by ruanhang1993** [comment]
@EMsnap I think this PR should be modified. Actually all captured tables are not equals to remainingTables + alreadyProcessedTables. The method `computeTablesPendingSnapshot` may be helpful to understand it.
图片 1

File: flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java [hunk 1]
```diff
@@ -300,6 +300,7 @@ private void splitTable(TableId nextTable) {
                 remainingSplits.addAll(schemaLessSnapshotSplits);
                 if (!chunkSplitter.hasNextChunk()) {
                     remainingTables.remove(nextTable);
+                    addAlreadyProcessedTablesIfNotExists(nextTable);
```
Comment (ruanhang1993) [inline flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java:303]: We should change the code in `captureNewlyAddedTables` instead of changing the location of `addAlreadyProcessedTablesIfNotExists`.

**Comment by EMsnap** [comment]
> @EMsnap I think this PR should be modified. Actually all captured tables are not equals to remainingTables + alreadyProcessedTables. The method `computeTablesPendingSnapshot` may be helpful to understand it. 图片 1

Thanks for the reply, I'll take a look. 
But where is this computeTablesPendingSnapshot method located? I can't find it on the master branch

File: flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java (hunk 1 above)
Comment (EMsnap) [reply flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java:303]: Noted, I'll change the implementation asap

**Comment by ruanhang1993** [comment]
> computeTablesPendingSnapshot

Sorry, the `computeTablesPendingSnapshot` are not provided before the Flink 1.18. Please ignore that.

**Comment by ruanhang1993** [comment]
@EMsnap Thanks for the work. We try to fix this in the version 2.4.1. So I provide a new changes to fix this.

**Review by ruanhang1993 — APPROVED** [review]
LGTM

**Comment by EMsnap** [comment]
> @EMsnap Thanks for the work. We try to fix this in the version 2.4.1. So I provide a new changes to fix this.

Thanks for your reply and your new changes, great job !
