### PR TITLE
[mysql] Fix assigning duplicate snapshot splits when enable scan newly added tables

### LINKED ISSUE #2095: [Bug] Duplicate Split which cause duplicate data when open scanNewlyAddedTableEnabled
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

FLINK 1.13 - FLINK 1.16 (all version)

### Flink CDC version

Latest

### Database and its version

Mysql (all version)

### Minimal reproduce step

1、open scan.newly-added-table.enabled in mysql source
2、running in snapshot phase
3、stop and restart the job

image

The chunks that generated before stop will be generated again in the second start
So the data will be duplicated, this is unacceptable when table contains large chunk of data which will cause a lot of extra tim e

### What did you expect to see?

no duplicate split when job restarts

### What did you see instead?

duplicate split when job restarts

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by ruanhang1993**
Fix #2095 in 2.4.

### CODE REVIEW

File: flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java [hunk 1]
```diff
@@ -209,11 +211,17 @@ private void captureNewlyAddedTables() {
...
+                        remainingSplits.stream()
+                                .map(MySqlSnapshotSplit::getTableId)
+                                .collect(Collectors.toList());
+                tablesToRemove.addAll(tablesInRemainingSplits);
                 tablesToRemove.addAll(remainingTables);
                 tablesToRemove.removeAll(newlyAddedTables);
 
                 newlyAddedTables.removeAll(alreadyProcessedTables);
+                newlyAddedTables.removeAll(tablesInRemainingSplits);
                 newlyAddedTables.removeAll(remainingTables);
```
Comment (leonardBang) [inline flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/MySqlSnapshotSplitAssigner.java:225]:
```
               final List<TableId> matchedCapturedTables = discoverCapturedTables(jdbc, sourceConfig);

                // Get the removed tables with the new table filter
                List<TableId> tablesInRemainingSplits =
                        remainingSplits.stream()
                                .map(MySqlSnapshotSplit::getTableId)
                                .collect(Collectors.toList());
                Set<TableId> tablesToRemove = new HashSet<>();
                tablesToRemove.addAll(alreadyProcessedTables
                tablesToRemove.addAll(remainingTables);
                tablesToRemove.addAll(tablesInRemainingSplits);
                tablesToRemove.removeAll(matchedCapturedTables);

                matchedCapturedTables.removeAll(alreadyProcessedTables);
                matchedCapturedTables.removeAll(remainingTables);
                matchedCapturedTables.removeAll(tablesInRemainingSplits);
                Set<TableId> newlyAddedTables = matchedCapturedTables;
```

**Review by leonardBang — APPROVED** [review]
Nice!, +1
