### PR TITLE
[postgres] Fix data lost problem when new lsn committed to slot between snapshotState and notifyCheckpointComplete

### LINKED ISSUE #2538: [Bug][postgres-cdc] Data lost when new lsn committed to slot between snapshotState and notifyCheckpointComplete
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.17.0

### Flink CDC version

2.5-SNAPSHOT

### Database and its version

I have added e2e test to reproduce data lost problem: PostgresSourceITCase#testNewLsnCommittedWhenCheckpoint
see https://github.com/lzshlzsh/flink-cdc-connectors/commit/24bf841b65562262116c383d3d1b1613f1e261ee

### Minimal reproduce step

run e2e tests PostgresSourceITCase#testNewLsnCommittedWhenCheckpoint, and the firstPartStreamEvents lost.
see https://github.com/lzshlzsh/flink-cdc-connectors/commit/24bf841b65562262116c383d3d1b1613f1e261ee

### What did you expect to see?

run e2e tests PostgresSourceITCase#testNewLsnCommittedWhenCheckpoint, both firstPartStreamEvents and secondPartStreamEvents should appear.

see https://github.com/lzshlzsh/flink-cdc-connectors/commit/e3bd9013d79bad5635400c9e27f3db05bdf39092

### What did you see instead?

nothing

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by lzshlzsh**
this fix #2538

### CODE REVIEW

**Comment by lzshlzsh** [comment]
@loserwang1024 @leonardBang Would you help to review this pr.

File: flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/fetch/PostgresStreamFetchTask.java [hunk 1]
```diff
@@ -128,6 +128,18 @@ public void commitCurrentOffset() {
...
                                     .getOffset()
                                     .get(PostgresOffsetContext.LAST_COMMIT_LSN_KEY);
+
+            if (split != null && split.isStreamSplit()) {
+                // Note: We should commit the LSN from the splits in the checkpoint, not the
+                // context's LSN. This is because after the source completes the snapshot function,
+                // it will begin consuming data from the PostgreSQL replication stream.
+                // Within PostgresStreamingChangeEventSource, the context's LSN will be updated.
+                commitLsn =
+                        ((PostgresOffset) split.asStreamSplit().getStartingOffset())
```
Comment (loserwang1024) [inline flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/fetch/PostgresStreamFetchTask.java:138]: The biggest problem of this PR: each split is read between [start, end). If commit starting offset  and then failover. The message of starting offset will lose.

File: flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/IncrementalSourceReader.java [hunk 2]
```diff
@@ -129,12 +136,27 @@ public List<SourceSplitBase> snapshotState(long checkpointId) {
...
-        dialect.notifyCheckpointComplete(checkpointId);
+        if (checkpointId > maxCompletedCheckpointId) {
+            SourceSplitBase split = lastCheckPointStreamSplit.get(checkpointId);
+            dialect.notifyCheckpointComplete(checkpointId, split);
+            lastCheckPointStreamSplit.headMap(checkpointId).clear();
+            maxCompletedCheckpointId = checkpointId;
+        }
     }
 
     @Override
```
Comment (loserwang1024) [inline flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/IncrementalSourceReader.java:162]: Remove finished splits from lastCheckPointStreamSplit, nor memory leak will occur.

**Review by loserwang1024 — COMMENTED** [review]
@lzshlzsh, thanks a lot for your contribution. I have provided some advice below：

File: flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/IncrementalSourceReader.java [hunk 3]
```diff
@@ -79,6 +80,10 @@ public class IncrementalSourceReader<T, C extends SourceConfig>
     private final C sourceConfig;
     private final DataSourceDialect<C> dialect;
 
+    private final TreeMap<Long, SourceSplitBase> lastCheckPointStreamSplit;
+
+    private long maxCompletedCheckpointId;
+
     public IncrementalSourceReader(
```
[the remark this answers is not in the document]
Comment (lzshlzsh) [reply flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/IncrementalSourceReader.java:87]: good idea

File: flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/fetch/PostgresStreamFetchTask.java (hunk 1 above)
Comment (lzshlzsh) [reply flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/fetch/PostgresStreamFetchTask.java:138]: Perhaps what you're talking about is the start and end of the primary key?
This PR is an attempt to solve the data lost problem in the stream stage, where the root cause is that the offset of the streamsplit in the checkpoint state lags behind the confirmed_flush_lsn of the postgres slot, the wal data between them has been lost, such as the reproducing test case added by the first commit of this PR.

There is no problem in scan/snapshot stage.

File: flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/dialect/DataSourceDialect.java [hunk 4]
```diff
@@ -79,4 +79,13 @@ public interface DataSourceDialect<C extends SourceConfig>
      */
     @Override
     default void notifyCheckpointComplete(long checkpointId) throws Exception {}
```
Comment (loserwang1024) [inline flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/dialect/DataSourceDialect.java:81]: It seem that this method is no longer use

File: flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/fetch/PostgresStreamFetchTask.java [hunk 5]
```diff
@@ -128,6 +128,18 @@ public void commitCurrentOffset() {
                             postgresOffsetContext
                                     .getOffset()
                                     .get(PostgresOffsetContext.LAST_COMMIT_LSN_KEY);
```
Comment (loserwang1024) [inline flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/fetch/PostgresStreamFetchTask.java:130]: It no longer need this code, because only streamingSlit is allowed to commitCurrentOffset. More over, `LAST_COMMIT_LSN_KEY` is update by `Begin` or `Commit` rather than message (See PostgresStreamingChangeEventSource#processMessages -> PostgresStreamingChangeEventSource#commitMessage -> PostgresOffsetContext#updateCommitPosition).

Comment (lzshlzsh) [reply flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/fetch/PostgresStreamFetchTask.java:130]: > It no longer need this code, because only streamingSlit is allowed to commitCurrentOffset. More over, `LAST_COMMIT_LSN_KEY` is update by `Begin` or `Commit` rather than message (See PostgresStreamingChangeEventSource#processMessages -> PostgresStreamingChangeEventSource#commitMessage -> PostgresOffsetContext#updateCommitPosition).

Thanks for your review, I will modify the code according to your suggestion。
 Yes, your are right, LAST_COMMIT_LSN_KEY is updated by Begin or commit message. 

I want to explain the data lost problem in more detail, because the problem happens on our online when failover. After apply this pr's fix,  there have been no data loss so far.

If checkpoint succeeds and before notifyCheckpoint's commit confirmed_flush_lsn finishes, there's a table UPDATE event arrives, the event appears as BEGIN/UPDATE/COMMIT LSN sequence, the notifyCheckpoint will commit COMMIT's LSN to slot. If failover happends at this time and will restore from this checkpoint, it will begin consume from the slot's confirmed_flush_lsn(that is COMMIT's LSN), nor the LSN of the streamsplit's lsn of checkpoint, because streamsplit's lsn < slot's confirmed_flush_lsn。From the high level view, the table's UPDATE event is lost.

Comment (loserwang1024) [reply flink-connector-postgres-cdc/src/main/java/com/ververica/cdc/connectors/postgres/source/fetch/PostgresStreamFetchTask.java:130]: Thanks a lot for your explain, I totally agree with you.  Moreover, I have also found that Postgres offset commit is no bound to checkpoint id before your PR.  If do checkpoint five consecutive times,  then the first one is done(then notifyCheckpoint) ,  the offset of the fifth checkpoint will be commit. If failover and restart from first checkpoint, Wal-Log between [first_checkpoint, five_checkpoint) will be recycled.

File: flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/IncrementalSourceReader.java [hunk 6]
```diff
@@ -129,12 +136,27 @@ public List<SourceSplitBase> snapshotState(long checkpointId) {
         // add stream splits who are uncompleted
         stateSplits.addAll(uncompletedStreamSplits.values());
 
+        for (SourceSplitBase split : stateSplits) {
+            if (split.isStreamSplit()) {
+                lastCheckPointStreamSplit.put(checkpointId, split.asStreamSplit());
+                LOG.debug(
+                        "snapshot stream split, checkpoint id {}, stream split {}",
```
[the remark this answers is not in the document]
Comment (lzshlzsh) [reply flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/IncrementalSourceReader.java]: done

File: flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/IncrementalSourceReader.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (lzshlzsh) [reply flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/IncrementalSourceReader.java:82]: @loserwang1024 Thanks for review, IncrementalSourceReaderWithCommit is added, and is used for postgres-cdc currently.

File: flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/dialect/DataSourceDialect.java (hunk 4 above)
Comment (lzshlzsh) [reply flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/dialect/DataSourceDialect.java:82]: Have to provide a default implementation, as the supper.CheckpointListener does not have a default implementation.

File: flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/IncrementalSourceReader.java (hunk 2 above)
Comment (lzshlzsh) [reply flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/IncrementalSourceReader.java]: Thanks for your review. Yes, StreamSplit of current checkpointId should remove.

File: flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/IncrementalSourceReader.java [hunk 7]
```diff
@@ -129,12 +136,27 @@ public List<SourceSplitBase> snapshotState(long checkpointId) {
         // add stream splits who are uncompleted
         stateSplits.addAll(uncompletedStreamSplits.values());
 
+        for (SourceSplitBase split : stateSplits) {
+            if (split.isStreamSplit()) {
+                lastCheckPointStreamSplit.put(checkpointId, split.asStreamSplit());
```
[the remark this answers is not in the document]
Comment (lzshlzsh) [reply flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/IncrementalSourceReader.java]: > what about this? In for loop, if not just one meet the requirement, later one will override the later one in heap

The code has been moved to IncrementalSourceReaderWithCommit. Currently,  only StreamSplit is need, and should be just one StreamSplit for a checkpoint. Maybe a TreeMap<Long, StreamSplit> is enough, instead of TreeMap<Long, List<>>, do you think so?

[the remark this answers is not in the document]
Comment (loserwang1024) [reply flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/IncrementalSourceReader.java]: Thanks for your explain. It seems that TreeMap<Long, StreamSplit> are different of same streamSplit. Each streamSplit contains lots of redundant informations, such as tableSchemas and finishedSnapshotSplitInfos. It seems that only startingOffset is what we need. Why not change TreeMap<Long, StreamSplit> to TreeMap<Long, Offset>?

[the remark this answers is not in the document]
Comment (lzshlzsh) [reply flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/IncrementalSourceReader.java]: Thanks and gree with you

[the remark this answers is not in the document]
Comment (lzshlzsh) [reply flink-cdc-base/src/main/java/com/ververica/cdc/connectors/base/source/reader/IncrementalSourceReader.java]: > Thanks for your explain. It seems that TreeMap<Long, StreamSplit> are different versions of same streamSplit. Each streamSplit contains lots of redundant informations, such as tableSchemas and finishedSnapshotSplitInfos. It seems that only startingOffset is what we need. Why not change TreeMap<Long, StreamSplit> to TreeMap<Long, Offset>?

Have made the modifications according to your suggestions. Could you please do a review if you have time?

**Review by loserwang1024 — APPROVED** [review]
LGTM

**Comment by lzshlzsh** [comment]
> @lzshlzsh would you like to rebase the PR to latest master so that we can merge it

Sorry, I saw the message too late。I'll rebase it.

**Comment by lzshlzsh** [comment]
> @lzshlzsh would you like to rebase the PR to latest master so that we can merge it

@leonardBang have rebased on master， would you help to have a review?

**Comment by loserwang1024** [comment]
@leonardBang , CC

**Review by leonardBang — APPROVED** [review]
Thanks @lzshlzsh for the contribution and @loserwang1024 for the review work, LGTM
